<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SchoolSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        DB::table('schools')->delete();
        
        DB::table('schools')->insert(array (
             
            array (
                'id' => 1,
                'name' => 'York House',
                'address' => '4176 Alexandra St',
                'city' => 'Vancouver',
                'latitude' => '49.2490070',
                'longitude' => '-123.1411440',

                'type' => 1,
                'is_public' => 0,
                'school_zone' => '',
                'ranking_city' => NULL,
                'ranking_state' => NULL,
                'ranking_city_5_years' => NULL,
                'ranking_state_5_years' => NULL,
                'school_img_url' => NULL,
            ),
             
            array (
                'id' => 2,
                'name' => 'Little Flower',
                'address' => '4195 Alexandra St',
                'city' => 'Vancouver',
                'latitude' => '49.2486960',
                'longitude' => '-123.1421100',

                'type' => 1,
                'is_public' => 0,
                'school_zone' => '',
                'ranking_city' => NULL,
                'ranking_state' => NULL,
                'ranking_city_5_years' => NULL,
                'ranking_state_5_years' => NULL,
                'school_img_url' => NULL,
            ),
             
            array (
                'id' => 3,
                'name' => 'Southridge',
                'address' => '2656 160 St',
                'city' => 'Surrey',
                'latitude' => '49.0501070',
                'longitude' => '-122.7789210',

                'type' => 1,
                'is_public' => 0,
                'school_zone' => '',
                'ranking_city' => NULL,
                'ranking_state' => NULL,
                'ranking_city_5_years' => NULL,
                'ranking_state_5_years' => NULL,
                'school_img_url' => NULL,
            ),
             
            array (
                'id' => 4,
                'name' => 'Crofton House',
                'address' => '3200 41st Ave W',
                'city' => 'Vancouver',
                'latitude' => '49.2345570',
                'longitude' => '-123.1768570',

                'type' => 1,
                'is_public' => 0,
                'school_zone' => '',
                'ranking_city' => NULL,
                'ranking_state' => NULL,
                'ranking_city_5_years' => NULL,
                'ranking_state_5_years' => NULL,
                'school_img_url' => NULL,
            ),
             
            array (
                'id' => 5,
                'name' => 'West Point Grey',
                'address' => '4125 8th Ave W',
                'city' => 'Vancouver',
                'latitude' => '27.4931540',
                'longitude' => '-82.6009510',

                'type' => 1,
                'is_public' => 0,
                'school_zone' => '',
                'ranking_city' => NULL,
                'ranking_state' => NULL,
                'ranking_city_5_years' => NULL,
                'ranking_state_5_years' => NULL,
                'school_img_url' => NULL,
            ),
             
            array (
                'id' => 6,
                'name' => 'St George\'s',
                'address' => '4175 W 29th Ave',
                'city' => 'Vancouver',
                'latitude' => '39.7585170',
                'longitude' => '-105.0413650',

                'type' => 1,
                'is_public' => 0,
                'school_zone' => '',
                'ranking_city' => NULL,
                'ranking_state' => NULL,
                'ranking_city_5_years' => NULL,
                'ranking_state_5_years' => NULL,
                'school_img_url' => NULL,
            ),
             
            array (
                'id' => 7,
                'name' => 'Collingwood',
                'address' => '70 Morven Dr',
                'city' => 'West Vancouver',
                'latitude' => '49.3606470',
                'longitude' => '-123.1196220',

                'type' => 1,
                'is_public' => 0,
                'school_zone' => '',
                'ranking_city' => NULL,
                'ranking_state' => NULL,
                'ranking_city_5_years' => NULL,
                'ranking_state_5_years' => NULL,
                'school_img_url' => NULL,
            ),
             
            array (
                'id' => 8,
                'name' => 'Relevant',
                'address' => '18620 56 Ave',
                'city' => 'Surrey',
                'latitude' => '43.1087800',
                'longitude' => '-85.9273510',

                'type' => 1,
                'is_public' => 0,
                'school_zone' => '',
                'ranking_city' => NULL,
                'ranking_state' => NULL,
                'ranking_city_5_years' => NULL,
                'ranking_state_5_years' => NULL,
                'school_img_url' => NULL,
            ),
             
            array (
                'id' => 9,
                'name' => 'St John\'s',
                'address' => '2215 10th Ave W',
                'city' => 'Vancouver',
                'latitude' => '46.1985860',
                'longitude' => '-119.1507370',
                
                'type' => 1,
                'is_public' => 0,
                'school_zone' => '',
                'ranking_city' => NULL,
                'ranking_state' => NULL,
                'ranking_city_5_years' => NULL,
                'ranking_state_5_years' => NULL,
                'school_img_url' => NULL,
            ),
             
            array (
                'id' => 10,
                'name' => 'Vancouver College',
                'address' => '5400 Cartier St',
                'city' => 'Vancouver',
                'latitude' => '49.2360170',
                'longitude' => '-123.1359530',
                'type' => 1,
                'is_public' => 0,
                'school_zone' => '',
                'ranking_city' => NULL,
                'ranking_state' => NULL,
                'ranking_city_5_years' => NULL,
                'ranking_state_5_years' => NULL,
                'school_img_url' => NULL,
            ),
             
            array (
                'id' => 11,
                'name' => 'Meadowridge',
                'address' => '12224 240 St',
                'city' => 'Maple Ridge',
                'latitude' => '49.2245540',
                'longitude' => '-122.5568410',
                'type' => 1,
                'is_public' => 0,
                'school_zone' => '',
                'ranking_city' => NULL,
                'ranking_state' => NULL,
                'ranking_city_5_years' => NULL,
                'ranking_state_5_years' => NULL,
                'school_img_url' => NULL,
            ),
             
            array (
                'id' => 12,
                'name' => 'Southpointe',
                'address' => '1741 56 St',
                'city' => 'Delta',
                'latitude' => '49.0340580',
                'longitude' => '-123.0686810',
                'type' => 1,
                'is_public' => 0,
                'school_zone' => '',
                'ranking_city' => NULL,
                'ranking_state' => NULL,
                'ranking_city_5_years' => NULL,
                'ranking_state_5_years' => NULL,
                'school_img_url' => NULL,
            ),
             
            array (
                'id' => 13,
                'name' => 'Mulgrave',
                'address' => '2330 Cypress Lane',
                'city' => 'West Vancouver',
                'latitude' => '49.2650970',
                'longitude' => '-123.1480570',
                'type' => 1,
                'is_public' => 0,
                'school_zone' => '',
                'ranking_city' => NULL,
                'ranking_state' => NULL,
                'ranking_city_5_years' => NULL,
                'ranking_state_5_years' => NULL,
                'school_img_url' => NULL,
            ),
             
            array (
                'id' => 14,
                'name' => 'University Hill Secondary',
                'address' => '3250 East Mall',
                'city' => 'Vancouver',
                'latitude' => '49.2542940',
                'longitude' => '-123.2389310',
                'type' => 1,
                'is_public' => 0,
                'school_zone' => '',
                'ranking_city' => NULL,
                'ranking_state' => NULL,
                'ranking_city_5_years' => NULL,
                'ranking_state_5_years' => NULL,
                'school_img_url' => NULL,
            ),
             
            array (
                'id' => 15,
                'name' => 'Regent Christian',
                'address' => '15100 66A Ave',
                'city' => 'Surrey',
                'latitude' => '49.1235180',
                'longitude' => '-122.8043500',
                'type' => 1,
                'is_public' => 0,
                'school_zone' => '',
                'ranking_city' => NULL,
                'ranking_state' => NULL,
                'ranking_city_5_years' => NULL,
                'ranking_state_5_years' => NULL,
                'school_img_url' => NULL,
            ),
             
            array (
                'id' => 16,
                'name' => 'Richmond Christian',
                'address' => '5240 Woodwards Rd',
                'city' => 'Richmond',
                'latitude' => '49.1430940',
                'longitude' => '-123.1665320',
                'type' => 1,
                'is_public' => 0,
                'school_zone' => '',
                'ranking_city' => NULL,
                'ranking_state' => NULL,
                'ranking_city_5_years' => NULL,
                'ranking_state_5_years' => NULL,
                'school_img_url' => NULL,
            ),
             
            array (
                'id' => 17,
                'name' => 'St Thomas Aquinas',
                'address' => '541 Keith Rd W',
                'city' => 'North Vancouver',
                'latitude' => '49.3308530',
                'longitude' => '-123.1312400',
                
                'type' => 1,
                'is_public' => 0,
                'school_zone' => '',
                'ranking_city' => NULL,
                'ranking_state' => NULL,
                'ranking_city_5_years' => NULL,
                'ranking_state_5_years' => NULL,
                'school_img_url' => NULL,
            ),
             
            array (
                'id' => 18,
                'name' => 'Lord Byng Secondary',
                'address' => '3939 W. 16th Ave.',
                'city' => 'Vancouver',
                'latitude' => '49.2588710',
                'longitude' => '-123.1923580',
                
                'type' => 1,
                'is_public' => 1,
                'school_zone' => '',
                'ranking_city' => NULL,
                'ranking_state' => NULL,
                'ranking_city_5_years' => NULL,
                'ranking_state_5_years' => NULL,
                'school_img_url' => NULL,
            ),
             
            array (
                'id' => 19,
                'name' => 'St Thomas More',
                'address' => '7450 12th Ave',
                'city' => 'Burnaby',
                'latitude' => '49.2153830',
                'longitude' => '-122.9376340',
                
                'type' => 1,
                'is_public' => 0,
                'school_zone' => '',
                'ranking_city' => NULL,
                'ranking_state' => NULL,
                'ranking_city_5_years' => NULL,
                'ranking_state_5_years' => NULL,
                'school_img_url' => NULL,
            ),
             
            array (
                'id' => 20,
                'name' => 'Pacific Academy',
                'address' => '10238 168 St',
                'city' => 'Surrey',
                'latitude' => '49.1888210',
                'longitude' => '-122.7552010',
                
                'type' => 1,
                'is_public' => 0,
                'school_zone' => '',
                'ranking_city' => NULL,
                'ranking_state' => NULL,
                'ranking_city_5_years' => NULL,
                'ranking_state_5_years' => NULL,
                'school_img_url' => NULL,
            ),
             
            array (
                'id' => 22,
                'name' => 'Langley Christian',
                'address' => '22930 48 Ave',
                'city' => 'Langley',
                'latitude' => '49.0885570',
                'longitude' => '-122.5894670',
                
                'type' => 1,
                'is_public' => 0,
                'school_zone' => '',
                'ranking_city' => NULL,
                'ranking_state' => NULL,
                'ranking_city_5_years' => NULL,
                'ranking_state_5_years' => NULL,
                'school_img_url' => NULL,
            ),
             
            array (
                'id' => 23,
                'name' => 'Sentinel Secondary',
                'address' => '1250 Chartwell Dr',
                'city' => 'West Vancouver',
                'latitude' => '49.3463180',
                'longitude' => '-123.1494240',
                
                'type' => 1,
                'is_public' => 1,
                'school_zone' => '',
                'ranking_city' => NULL,
                'ranking_state' => NULL,
                'ranking_city_5_years' => NULL,
                'ranking_state_5_years' => NULL,
                'school_img_url' => NULL,
            ),
             
            array (
                'id' => 24,
                'name' => 'King David',
                'address' => '5718 Willow St',
                'city' => 'Vancouver',
                'latitude' => '49.2334480',
                'longitude' => '-123.1227910',
                
                'type' => 1,
                'is_public' => 0,
                'school_zone' => '',
                'ranking_city' => NULL,
                'ranking_state' => NULL,
                'ranking_city_5_years' => NULL,
                'ranking_state_5_years' => NULL,
                'school_img_url' => NULL,
            ),
             
            array (
                'id' => 25,
                'name' => 'Archbishop Carney',
                'address' => '1335 Dominion Ave',
                'city' => 'Coquitlam',
                'latitude' => '49.2591750',
                'longitude' => '-122.7516200',
                
                'type' => 1,
                'is_public' => 0,
                'school_zone' => '',
                'ranking_city' => NULL,
                'ranking_state' => NULL,
                'ranking_city_5_years' => NULL,
                'ranking_state_5_years' => NULL,
                'school_img_url' => NULL,
            ),
             
            array (
                'id' => 26,
                'name' => 'Deer Lake SDA',
                'address' => '5550 Gilpin St',
                'city' => 'Burnaby',
                'latitude' => '49.2414720',
                'longitude' => '-122.9832280',
                
                'type' => 1,
                'is_public' => 0,
                'school_zone' => '',
                'ranking_city' => NULL,
                'ranking_state' => NULL,
                'ranking_city_5_years' => NULL,
                'ranking_state_5_years' => NULL,
                'school_img_url' => NULL,
            ),
             
            array (
                'id' => 27,
                'name' => 'Langley Fundamental Middle School',
                'address' => '21250 - 42nd Ave',
                'city' => 'Langley',
                'latitude' => '49.0780220',
                'longitude' => '-122.6348440',
                
                'type' => 1,
                'is_public' => 1,
                'school_zone' => '',
                'ranking_city' => NULL,
                'ranking_state' => NULL,
                'ranking_city_5_years' => NULL,
                'ranking_state_5_years' => NULL,
                'school_img_url' => NULL,
            ),
             
            array (
                'id' => 28,
                'name' => 'Dr. Charles Best Secondary',
                'address' => '2525 Como Lake Avenue',
                'city' => 'Coquitlam',
                'latitude' => '49.2637480',
                'longitude' => '-122.8204530',
                
                'type' => 1,
                'is_public' => 1,
                'school_zone' => '',
                'ranking_city' => NULL,
                'ranking_state' => NULL,
                'ranking_city_5_years' => NULL,
                'ranking_state_5_years' => NULL,
                'school_img_url' => NULL,
            ),
             
            array (
                'id' => 29,
                'name' => 'Handsworth Secondary',
                'address' => '1044 Edgewood Road',
                'city' => 'North Vancouver',
                'latitude' => '49.3521940',
                'longitude' => '-123.1003690',
                
                'type' => 1,
                'is_public' => 1,
                'school_zone' => '',
                'ranking_city' => NULL,
                'ranking_state' => NULL,
                'ranking_city_5_years' => NULL,
                'ranking_state_5_years' => NULL,
                'school_img_url' => NULL,
            ),
             
            array (
                'id' => 30,
                'name' => 'Holy Cross',
                'address' => '16193 88 Ave',
                'city' => 'Surrey',
                'latitude' => '49.1630480',
                'longitude' => '-122.7745160',
                
                'type' => 1,
                'is_public' => 0,
                'school_zone' => '',
                'ranking_city' => NULL,
                'ranking_state' => NULL,
                'ranking_city_5_years' => NULL,
                'ranking_state_5_years' => NULL,
                'school_img_url' => NULL,
            ),
             
            array (
                'id' => 31,
                'name' => 'Lions Gate Christian',
                'address' => '919 Tollcross Rd',
                'city' => 'North Vancouver',
                'latitude' => '49.3133950',
                'longitude' => '-122.9944720',
                
                'type' => 1,
                'is_public' => 0,
                'school_zone' => '',
                'ranking_city' => NULL,
                'ranking_state' => NULL,
                'ranking_city_5_years' => NULL,
                'ranking_state_5_years' => NULL,
                'school_img_url' => NULL,
            ),
             
            array (
                'id' => 32,
                'name' => 'Richmond Secondary',
                'address' => '7171 Minoru Blvd',
                'city' => 'Richmond',
                'latitude' => '49.1610690',
                'longitude' => '-123.1423380',
                
                'type' => 1,
                'is_public' => 1,
                'school_zone' => '',
                'ranking_city' => NULL,
                'ranking_state' => NULL,
                'ranking_city_5_years' => NULL,
                'ranking_state_5_years' => NULL,
                'school_img_url' => NULL,
            ),
             
            array (
                'id' => 33,
                'name' => 'Point Grey Secondary',
                'address' => '5350 East Boulevard ',
                'city' => 'Vancouver',
                'latitude' => '49.2372510',
                'longitude' => '-123.1530480',
                
                'type' => 1,
                'is_public' => 1,
                'school_zone' => '',
                'ranking_city' => NULL,
                'ranking_state' => NULL,
                'ranking_city_5_years' => NULL,
                'ranking_state_5_years' => NULL,
                'school_img_url' => NULL,
            ),
             
            array (
                'id' => 34,
                'name' => 'Heritage Woods Secondary',
                'address' => '1300 David Ave',
                'city' => 'Port Moody',
                'latitude' => '49.2987490',
                'longitude' => '-122.8411440',
                
                'type' => 1,
                'is_public' => 1,
                'school_zone' => '',
                'ranking_city' => NULL,
                'ranking_state' => NULL,
                'ranking_city_5_years' => NULL,
                'ranking_state_5_years' => NULL,
                'school_img_url' => NULL,
            ),
             
            array (
                'id' => 35,
                'name' => 'Carver Christian',
                'address' => '7650 Sapperton Ave',
                'city' => 'Burnaby',
                'latitude' => '49.2366890',
                'longitude' => '-122.8991120',
                
                'type' => 1,
                'is_public' => 0,
                'school_zone' => '',
                'ranking_city' => NULL,
                'ranking_state' => NULL,
                'ranking_city_5_years' => NULL,
                'ranking_state_5_years' => NULL,
                'school_img_url' => NULL,
            ),
             
            array (
                'id' => 36,
                'name' => 'Semiahmoo Secondary',
                'address' => '1785 - 148 Street',
                'city' => 'Surrey',
                'latitude' => '49.0346000',
                'longitude' => '-122.8124730',
                
                'type' => 1,
                'is_public' => 1,
                'school_zone' => '',
                'ranking_city' => NULL,
                'ranking_state' => NULL,
                'ranking_city_5_years' => NULL,
                'ranking_state_5_years' => NULL,
                'school_img_url' => NULL,
            ),
             
            array (
                'id' => 37,
                'name' => 'McRoberts Secondary',
                'address' => '8980 Williams Road',
                'city' => 'Richmond',
                'latitude' => '49.1404120',
                'longitude' => '-123.1263600',
                
                'type' => 1,
                'is_public' => 1,
                'school_zone' => '',
                'ranking_city' => NULL,
                'ranking_state' => NULL,
                'ranking_city_5_years' => NULL,
                'ranking_state_5_years' => NULL,
                'school_img_url' => NULL,
            ),
             
            array (
                'id' => 38,
                'name' => 'Steveston - London Secondary',
                'address' => '6600 Williams Road,',
                'city' => 'Richmond',
                'latitude' => '49.1389710',
                'longitude' => '-123.1492950',
                
                'type' => 1,
                'is_public' => 1,
                'school_zone' => '',
                'ranking_city' => NULL,
                'ranking_state' => NULL,
                'ranking_city_5_years' => NULL,
                'ranking_state_5_years' => NULL,
                'school_img_url' => NULL,
            ),
             
            array (
                'id' => 39,
                'name' => 'Rockridge Secondary',
                'address' => '5350 Headland Dr',
                'city' => 'West Vancouver',
                'latitude' => '49.3499450',
                'longitude' => '-123.2540360',
                
                'type' => 1,
                'is_public' => 1,
                'school_zone' => '',
                'ranking_city' => NULL,
                'ranking_state' => NULL,
                'ranking_city_5_years' => NULL,
                'ranking_state_5_years' => NULL,
                'school_img_url' => NULL,
            ),
             
            array (
                'id' => 40,
                'name' => 'Burnett Secondary',
                'address' => '5011 Granville Avenue',
                'city' => 'Richmond',
                'latitude' => '49.1634130',
                'longitude' => '-123.1688900',
                
                'type' => 1,
                'is_public' => 1,
                'school_zone' => '',
                'ranking_city' => NULL,
                'ranking_state' => NULL,
                'ranking_city_5_years' => NULL,
                'ranking_state_5_years' => NULL,
                'school_img_url' => NULL,
            ),
             
            array (
                'id' => 41,
                'name' => 'Credo Christian',
                'address' => '21846 52 Ave',
                'city' => 'Langley',
                'latitude' => '49.0967530',
                'longitude' => '-122.6183810',
                
                'type' => 1,
                'is_public' => 0,
                'school_zone' => '',
                'ranking_city' => NULL,
                'ranking_state' => NULL,
                'ranking_city_5_years' => NULL,
                'ranking_state_5_years' => NULL,
                'school_img_url' => NULL,
            ),
             
            array (
                'id' => 42,
                'name' => 'Notre Dame',
                'address' => '2855 Parker St',
                'city' => 'Vancouver',
                'latitude' => '49.2758970',
                'longitude' => '-123.0464030',
                
                'type' => 1,
                'is_public' => 0,
                'school_zone' => '',
                'ranking_city' => NULL,
                'ranking_state' => NULL,
                'ranking_city_5_years' => NULL,
                'ranking_state_5_years' => NULL,
                'school_img_url' => NULL,
            ),
             
            array (
                'id' => 43,
                'name' => 'McMath Secondary',
                'address' => '4251 Garry Street',
                'city' => 'Richmond',
                'latitude' => '49.1306810',
                'longitude' => '-123.1788670',
                
                'type' => 1,
                'is_public' => 1,
                'school_zone' => '',
                'ranking_city' => NULL,
                'ranking_state' => NULL,
                'ranking_city_5_years' => NULL,
                'ranking_state_5_years' => NULL,
                'school_img_url' => NULL,
            ),
             
            array (
                'id' => 44,
                'name' => 'Elgin Park Secondary',
                'address' => '13484 - 24 Avenue',
                'city' => 'Surrey',
                'latitude' => '49.0455530',
                'longitude' => '-122.8485890',
                
                'type' => 1,
                'is_public' => 1,
                'school_zone' => '',
                'ranking_city' => NULL,
                'ranking_state' => NULL,
                'ranking_city_5_years' => NULL,
                'ranking_state_5_years' => NULL,
                'school_img_url' => NULL,
            ),
             
            array (
                'id' => 45,
                'name' => 'Magee Secondary',
                'address' => '6360 Maple Street',
                'city' => 'Vancouver',
                'latitude' => '45.6529300',
                'longitude' => '-122.6808000',
                
                'type' => 1,
                'is_public' => 1,
                'school_zone' => '',
                'ranking_city' => NULL,
                'ranking_state' => NULL,
                'ranking_city_5_years' => NULL,
                'ranking_state_5_years' => NULL,
                'school_img_url' => NULL,
            ),
             
            array (
                'id' => 46,
                'name' => 'Prince of Wales Secondary',
                'address' => '2250 Eddington Dr',
                'city' => 'Vancouver',
                'latitude' => '49.2455510',
                'longitude' => '-123.1586050',
                
                'type' => 1,
                'is_public' => 1,
                'school_zone' => '',
                'ranking_city' => NULL,
                'ranking_state' => NULL,
                'ranking_city_5_years' => NULL,
                'ranking_state_5_years' => NULL,
                'school_img_url' => NULL,
            ),
             
            array (
                'id' => 47,
                'name' => 'Pinetree Secondary',
                'address' => '3000 Pinewood Avenue',
                'city' => 'Coquitlam',
                'latitude' => '49.2898490',
                'longitude' => '-122.7915910',
                
                'type' => 1,
                'is_public' => 1,
                'school_zone' => '',
                'ranking_city' => NULL,
                'ranking_state' => NULL,
                'ranking_city_5_years' => NULL,
                'ranking_state_5_years' => NULL,
                'school_img_url' => NULL,
            ),
             
            array (
                'id' => 48,
                'name' => 'Eric Hamber Secondary',
                'address' => '5025 Willow St',
                'city' => 'Vancouver',
                'latitude' => '49.2396770',
                'longitude' => '-123.1246000',
                
                'type' => 1,
                'is_public' => 1,
                'school_zone' => '',
                'ranking_city' => NULL,
                'ranking_state' => NULL,
                'ranking_city_5_years' => NULL,
                'ranking_state_5_years' => NULL,
                'school_img_url' => NULL,
            ),
             
            array (
                'id' => 49,
                'name' => 'Sir Winston Churchill Secondary',
                'address' => '7055 Heather St',
                'city' => 'Vancouver',
                'latitude' => '49.2203590',
                'longitude' => '-123.1254390',
                
                'type' => 1,
                'is_public' => 1,
                'school_zone' => '',
                'ranking_city' => NULL,
                'ranking_state' => NULL,
                'ranking_city_5_years' => NULL,
                'ranking_state_5_years' => NULL,
                'school_img_url' => NULL,
            ),
             
            array (
                'id' => 50,
                'name' => 'Windsor Secondary',
                'address' => '931 Broadview Drive',
                'city' => 'North Vancouver',
                'latitude' => '49.3137110',
                'longitude' => '-122.9977430',
                
                'type' => 1,
                'is_public' => 1,
                'school_zone' => '',
                'ranking_city' => NULL,
                'ranking_state' => NULL,
                'ranking_city_5_years' => NULL,
                'ranking_state_5_years' => NULL,
                'school_img_url' => NULL,
            ),
             
            array (
                'id' => 51,
                'name' => 'Stratford Hall',
                'address' => '3000 Commercial Dr',
                'city' => 'Vancouver',
                'latitude' => '49.2574790',
                'longitude' => '-123.0694840',
                
                'type' => 1,
                'is_public' => 0,
                'school_zone' => '',
                'ranking_city' => NULL,
                'ranking_state' => NULL,
                'ranking_city_5_years' => NULL,
                'ranking_state_5_years' => NULL,
                'school_img_url' => NULL,
            ),
             
            array (
                'id' => 52,
                'name' => 'R.E. Mountain Secondary',
                'address' => '7755 - 202A Street',
                'city' => 'Langley',
                'latitude' => '49.1438680',
                'longitude' => '-122.6624090',
                
                'type' => 1,
                'is_public' => 1,
                'school_zone' => '',
                'ranking_city' => NULL,
                'ranking_state' => NULL,
                'ranking_city_5_years' => NULL,
                'ranking_state_5_years' => NULL,
                'school_img_url' => NULL,
            ),
             
            array (
                'id' => 53,
                'name' => 'Fleetwood Park Secondary',
                'address' => '7940 - 156 Street ',
                'city' => 'Surrey',
                'latitude' => '49.1478550',
                'longitude' => '-122.7890820',
                
                'type' => 1,
                'is_public' => 1,
                'school_zone' => '',
                'ranking_city' => NULL,
                'ranking_state' => NULL,
                'ranking_city_5_years' => NULL,
                'ranking_state_5_years' => NULL,
                'school_img_url' => NULL,
            ),
             
            array (
                'id' => 54,
                'name' => 'Surrey Christian',
                'address' => '9115 160 St',
                'city' => 'Surrey',
                'latitude' => '49.1685720',
                'longitude' => '-122.7791180',
                
                'type' => 1,
                'is_public' => 0,
                'school_zone' => '',
                'ranking_city' => NULL,
                'ranking_state' => NULL,
                'ranking_city_5_years' => NULL,
                'ranking_state_5_years' => NULL,
                'school_img_url' => NULL,
            ),
             
            array (
                'id' => 55,
                'name' => 'Walnut Grove Secondary',
                'address' => '8919 Walnut Grove Drive',
                'city' => 'Langley',
                'latitude' => '49.1660680',
                'longitude' => '-122.6389910',
                
                'type' => 1,
                'is_public' => 1,
                'school_zone' => '',
                'ranking_city' => NULL,
                'ranking_state' => NULL,
                'ranking_city_5_years' => NULL,
                'ranking_state_5_years' => NULL,
                'school_img_url' => NULL,
            ),
             
            array (
                'id' => 56,
                'name' => 'Gleneagle Secondary',
                'address' => '1195 Lansdowne Dr',
                'city' => 'Coquitlam',
                'latitude' => '49.2838680',
                'longitude' => '-122.8069540',
                
                'type' => 1,
                'is_public' => 1,
                'school_zone' => '',
                'ranking_city' => NULL,
                'ranking_state' => NULL,
                'ranking_city_5_years' => NULL,
                'ranking_state_5_years' => NULL,
                'school_img_url' => NULL,
            ),
             
            array (
                'id' => 57,
                'name' => 'Langley Fine Arts School',
                'address' => '9096 Trattle Road',
                'city' => 'Fort Langley',
                'latitude' => '49.1674510',
                'longitude' => '-122.5869730',
                
                'type' => 1,
                'is_public' => 1,
                'school_zone' => '',
                'ranking_city' => NULL,
                'ranking_state' => NULL,
                'ranking_city_5_years' => NULL,
                'ranking_state_5_years' => NULL,
                'school_img_url' => NULL,
            ),
             
            array (
                'id' => 58,
                'name' => 'Kitsilano Secondary',
                'address' => '2550 W. 10th Ave',
                'city' => 'Vancouver',
                'latitude' => '45.6737210',
                'longitude' => '-122.6802480',
                
                'type' => 1,
                'is_public' => 1,
                'school_zone' => '',
                'ranking_city' => NULL,
                'ranking_state' => NULL,
                'ranking_city_5_years' => NULL,
                'ranking_state_5_years' => NULL,
                'school_img_url' => NULL,
            ),
             
            array (
                'id' => 59,
                'name' => 'West Vancouver Secondary',
                'address' => '1750 Mathers Ave',
                'city' => 'West Vancouver',
                'latitude' => '49.3371480',
                'longitude' => '-123.1610680',
                
                'type' => 1,
                'is_public' => 1,
                'school_zone' => '',
                'ranking_city' => NULL,
                'ranking_state' => NULL,
                'ranking_city_5_years' => NULL,
                'ranking_state_5_years' => NULL,
                'school_img_url' => NULL,
            ),
             
            array (
                'id' => 60,
                'name' => 'David Thompson Secondary',
                'address' => '1755 E. 55th Ave',
                'city' => 'Vancouver',
                'latitude' => '49.2203180',
                'longitude' => '-123.0692940',
                
                'type' => 1,
                'is_public' => 1,
                'school_zone' => '',
                'ranking_city' => NULL,
                'ranking_state' => NULL,
                'ranking_city_5_years' => NULL,
                'ranking_state_5_years' => NULL,
                'school_img_url' => NULL,
            ),
             
            array (
                'id' => 61,
                'name' => 'New Westminster',
                'address' => '835 Eighth St',
                'city' => 'New Westminster',
                'latitude' => '49.2157810',
                'longitude' => '-122.9287910',
                
                'type' => 1,
                'is_public' => 1,
                'school_zone' => '',
                'ranking_city' => NULL,
                'ranking_state' => NULL,
                'ranking_city_5_years' => NULL,
                'ranking_state_5_years' => NULL,
                'school_img_url' => NULL,
            ),
             
            array (
                'id' => 62,
                'name' => 'North Surrey Secondary',
                'address' => '15945 - 96 Avenue',
                'city' => 'Surrey',
                'latitude' => '49.1783210',
                'longitude' => '-122.7805190',
                
                'type' => 1,
                'is_public' => 1,
                'school_zone' => '',
                'ranking_city' => NULL,
                'ranking_state' => NULL,
                'ranking_city_5_years' => NULL,
                'ranking_state_5_years' => NULL,
                'school_img_url' => NULL,
            ),
             
            array (
                'id' => 63,
                'name' => 'Seycove Secondary',
                'address' => '1204 Caledonia Avenue',
                'city' => 'North Vancouver',
                'latitude' => '49.3176640',
                'longitude' => '-122.9521970',
                
                'type' => 1,
                'is_public' => 1,
                'school_zone' => '',
                'ranking_city' => NULL,
                'ranking_state' => NULL,
                'ranking_city_5_years' => NULL,
                'ranking_state_5_years' => NULL,
                'school_img_url' => NULL,
            ),
             
            array (
                'id' => 64,
                'name' => 'White Rock Christian',
                'address' => '2265 152 St',
                'city' => 'Surrey',
                'latitude' => '49.0429290',
                'longitude' => '-122.8014580',
                
                'type' => 1,
                'is_public' => 0,
                'school_zone' => '',
                'ranking_city' => NULL,
                'ranking_state' => NULL,
                'ranking_city_5_years' => NULL,
                'ranking_state_5_years' => NULL,
                'school_img_url' => NULL,
            ),
             
            array (
                'id' => 65,
                'name' => 'Burnsview Secondary',
                'address' => '7658 112 Street',
                'city' => 'Delta',
                'latitude' => '49.1419240',
                'longitude' => '-122.9116330',
                
                'type' => 1,
                'is_public' => 1,
                'school_zone' => '',
                'ranking_city' => NULL,
                'ranking_state' => NULL,
                'ranking_city_5_years' => NULL,
                'ranking_state_5_years' => NULL,
                'school_img_url' => NULL,
            ),
             
            array (
                'id' => 66,
                'name' => 'Burnaby Central Secondary',
                'address' => '6011 Deer Lake Parkway ',
                'city' => 'Burnaby',
                'latitude' => '49.2434820',
                'longitude' => '-122.9750700',
                
                'type' => 1,
                'is_public' => 1,
                'school_zone' => '',
                'ranking_city' => NULL,
                'ranking_state' => NULL,
                'ranking_city_5_years' => NULL,
                'ranking_state_5_years' => NULL,
                'school_img_url' => NULL,
            ),
             
            array (
                'id' => 67,
                'name' => 'Maple Ridge Christian',
                'address' => '12140 203 St',
                'city' => 'Maple Ridge',
                'latitude' => '49.2233610',
                'longitude' => '-122.6563490',
                
                'type' => 1,
                'is_public' => 0,
                'school_zone' => '',
                'ranking_city' => NULL,
                'ranking_state' => NULL,
                'ranking_city_5_years' => NULL,
                'ranking_state_5_years' => NULL,
                'school_img_url' => NULL,
            ),
             
            array (
                'id' => 68,
                'name' => 'Riverside Secondary',
                'address' => '2215 Reeve Street',
                'city' => 'Port Coquitlam',
                'latitude' => '49.2558960',
                'longitude' => '-122.7892160',
                
                'type' => 1,
                'is_public' => 1,
                'school_zone' => '',
                'ranking_city' => NULL,
                'ranking_state' => NULL,
                'ranking_city_5_years' => NULL,
                'ranking_state_5_years' => NULL,
                'school_img_url' => NULL,
            ),
             
            array (
                'id' => 69,
                'name' => 'Argyle Secondary',
                'address' => '1131 Frederick Road',
                'city' => 'North Vancouver',
                'latitude' => '49.3411950',
                'longitude' => '-123.0420820',
                
                'type' => 1,
                'is_public' => 1,
                'school_zone' => '',
                'ranking_city' => NULL,
                'ranking_state' => NULL,
                'ranking_city_5_years' => NULL,
                'ranking_state_5_years' => NULL,
                'school_img_url' => NULL,
            ),
             
            array (
                'id' => 70,
                'name' => 'St Patrick\'s',
                'address' => '115 11th Ave E',
                'city' => 'Vancouver',
                'latitude' => '45.6295010',
                'longitude' => '-122.6714160',
                
                'type' => 1,
                'is_public' => 0,
                'school_zone' => '',
                'ranking_city' => NULL,
                'ranking_state' => NULL,
                'ranking_city_5_years' => NULL,
                'ranking_state_5_years' => NULL,
                'school_img_url' => NULL,
            ),
             
            array (
                'id' => 71,
                'name' => 'Fraser Heights Secondary',
                'address' => '16060 - 108 Avenue',
                'city' => 'Surrey',
                'latitude' => '49.1978730',
                'longitude' => '-122.7770130',
                
                'type' => 1,
                'is_public' => 1,
                'school_zone' => '',
                'ranking_city' => NULL,
                'ranking_state' => NULL,
                'ranking_city_5_years' => NULL,
                'ranking_state_5_years' => NULL,
                'school_img_url' => NULL,
            ),
             
            array (
                'id' => 72,
                'name' => 'Palmer Secondary',
                'address' => '8160 St. Albans Road',
                'city' => 'Richmond',
                'latitude' => '49.1538880',
                'longitude' => '-123.1294240',
                
                'type' => 1,
                'is_public' => 1,
                'school_zone' => '',
                'ranking_city' => NULL,
                'ranking_state' => NULL,
                'ranking_city_5_years' => NULL,
                'ranking_state_5_years' => NULL,
                'school_img_url' => NULL,
            ),
             
            array (
                'id' => 73,
                'name' => 'Vancouver Technical Secondary',
                'address' => '2600 E. Broadway',
                'city' => 'Vancouver',
                'latitude' => '49.2614040',
                'longitude' => '-123.0516840',
                
                'type' => 1,
                'is_public' => 1,
                'school_zone' => '',
                'ranking_city' => NULL,
                'ranking_state' => NULL,
                'ranking_city_5_years' => NULL,
                'ranking_state_5_years' => NULL,
                'school_img_url' => NULL,
            ),
             
            array (
                'id' => 74,
                'name' => 'Burnaby North Secondary',
                'address' => '751 Hammarskjold Drive',
                'city' => 'Burnaby',
                'latitude' => '49.2778050',
                'longitude' => '-122.9728480',
                
                'type' => 1,
                'is_public' => 1,
                'school_zone' => '',
                'ranking_city' => NULL,
                'ranking_state' => NULL,
                'ranking_city_5_years' => NULL,
                'ranking_state_5_years' => NULL,
                'school_img_url' => NULL,
            ),
             
            array (
                'id' => 75,
                'name' => 'Delta Secondary',
                'address' => '4615 51 Street',
                'city' => 'Delta',
                'latitude' => '49.0900000',
                'longitude' => '-123.0800000',
                
                'type' => 1,
                'is_public' => 1,
                'school_zone' => '',
                'ranking_city' => NULL,
                'ranking_state' => NULL,
                'ranking_city_5_years' => NULL,
                'ranking_state_5_years' => NULL,
                'school_img_url' => NULL,
            ),
             
            array (
                'id' => 76,
                'name' => 'Seaquam Secondary',
                'address' => '11584 Lyon Road',
                'city' => 'Delta',
                'latitude' => '49.1270370',
                'longitude' => '-122.9009030',
                
                'type' => 1,
                'is_public' => 1,
                'school_zone' => '',
                'ranking_city' => NULL,
                'ranking_state' => NULL,
                'ranking_city_5_years' => NULL,
                'ranking_state_5_years' => NULL,
                'school_img_url' => NULL,
            ),
             
            array (
                'id' => 77,
                'name' => 'Brookswood Secondary',
                'address' => '20902 - 37A Avenue',
                'city' => 'Langley',
                'latitude' => '49.0700410',
                'longitude' => '-122.6451570',
                
                'type' => 1,
                'is_public' => 1,
                'school_zone' => '',
                'ranking_city' => NULL,
                'ranking_state' => NULL,
                'ranking_city_5_years' => NULL,
                'ranking_state_5_years' => NULL,
                'school_img_url' => NULL,
            ),
             
            array (
                'id' => 78,
                'name' => 'Earl Marriott Secondary',
                'address' => '15751 - 16 Avenue',
                'city' => 'Surrey',
                'latitude' => '49.0312600',
                'longitude' => '-122.7854410',
                
                'type' => 1,
                'is_public' => 1,
                'school_zone' => '',
                'ranking_city' => NULL,
                'ranking_state' => NULL,
                'ranking_city_5_years' => NULL,
                'ranking_state_5_years' => NULL,
                'school_img_url' => NULL,
            ),
             
            array (
                'id' => 79,
                'name' => 'Lord Tweedsmuir Secondary',
                'address' => '6151 - 180 Street',
                'city' => 'Surrey',
                'latitude' => '49.1149810',
                'longitude' => '-122.7245610',
                
                'type' => 1,
                'is_public' => 1,
                'school_zone' => '',
                'ranking_city' => NULL,
                'ranking_state' => NULL,
                'ranking_city_5_years' => NULL,
                'ranking_state_5_years' => NULL,
                'school_img_url' => NULL,
            ),
             
            array (
                'id' => 80,
                'name' => 'Princess Margaret Secondary',
                'address' => '12870 - 72 Avenue',
                'city' => 'Surrey',
                'latitude' => '49.1334120',
                'longitude' => '-122.8660210',
                
                'type' => 1,
                'is_public' => 1,
                'school_zone' => '',
                'ranking_city' => NULL,
                'ranking_state' => NULL,
                'ranking_city_5_years' => NULL,
                'ranking_state_5_years' => NULL,
                'school_img_url' => NULL,
            ),
             
            array (
                'id' => 81,
                'name' => 'Moscrop Secondary',
                'address' => '4433 Moscrop Street',
                'city' => 'Burnaby',
                'latitude' => '49.2438340',
                'longitude' => '-123.0051750',
                
                'type' => 1,
                'is_public' => 1,
                'school_zone' => '',
                'ranking_city' => NULL,
                'ranking_state' => NULL,
                'ranking_city_5_years' => NULL,
                'ranking_state_5_years' => NULL,
                'school_img_url' => NULL,
            ),
             
            array (
                'id' => 82,
                'name' => 'Port Moody Secondary',
                'address' => '300 Albert St.',
                'city' => 'Port Moody',
                'latitude' => '49.2746740',
                'longitude' => '-122.8669610',
                
                'type' => 1,
                'is_public' => 1,
                'school_zone' => '',
                'ranking_city' => NULL,
                'ranking_state' => NULL,
                'ranking_city_5_years' => NULL,
                'ranking_state_5_years' => NULL,
                'school_img_url' => NULL,
            ),
             
            array (
                'id' => 83,
                'name' => 'South Delta Secondary',
                'address' => '750 53 Street',
                'city' => 'Delta',
                'latitude' => '49.0161610',
                'longitude' => '-123.0763210',
                
                'type' => 1,
                'is_public' => 1,
                'school_zone' => '',
                'ranking_city' => NULL,
                'ranking_state' => NULL,
                'ranking_city_5_years' => NULL,
                'ranking_state_5_years' => NULL,
                'school_img_url' => NULL,
            ),
             
            array (
                'id' => 84,
                'name' => 'Panorama Ridge Secondary',
                'address' => '13220 - 64 Avenue',
                'city' => 'Surrey',
                'latitude' => '49.1187910',
                'longitude' => '-122.8549870',
                
                'type' => 1,
                'is_public' => 1,
                'school_zone' => '',
                'ranking_city' => NULL,
                'ranking_state' => NULL,
                'ranking_city_5_years' => NULL,
                'ranking_state_5_years' => NULL,
                'school_img_url' => NULL,
            ),
             
            array (
                'id' => 85,
                'name' => 'Burnaby Mountain Secondary',
                'address' => '8800 Eastlake Drive',
                'city' => 'Burnaby',
                'latitude' => '49.2566580',
                'longitude' => '-122.9105540',
                
                'type' => 1,
                'is_public' => 1,
                'school_zone' => '',
                'ranking_city' => NULL,
                'ranking_state' => NULL,
                'ranking_city_5_years' => NULL,
                'ranking_state_5_years' => NULL,
                'school_img_url' => NULL,
            ),
             
            array (
                'id' => 86,
                'name' => 'Terry Fox Secondary',
                'address' => '1260 Riverwood Gate',
                'city' => 'Port Coquitlam',
                'latitude' => '49.2630070',
                'longitude' => '-122.7480780',
                
                'type' => 1,
                'is_public' => 1,
                'school_zone' => '',
                'ranking_city' => NULL,
                'ranking_state' => NULL,
                'ranking_city_5_years' => NULL,
                'ranking_state_5_years' => NULL,
                'school_img_url' => NULL,
            ),
             
            array (
                'id' => 87,
                'name' => 'D. W. Poppy Secondary',
                'address' => '23752 - 52nd Avenue',
                'city' => 'Langley',
                'latitude' => '49.0962380',
                'longitude' => '-122.5659790',
                
                'type' => 1,
                'is_public' => 1,
                'school_zone' => '',
                'ranking_city' => NULL,
                'ranking_state' => NULL,
                'ranking_city_5_years' => NULL,
                'ranking_state_5_years' => NULL,
                'school_img_url' => NULL,
            ),
             
            array (
                'id' => 88,
                'name' => 'Enver Creek Secondary',
                'address' => '14505 - 84 Avenue',
                'city' => 'Surrey',
                'latitude' => '49.1558280',
                'longitude' => '-122.8202500',
                
                'type' => 1,
                'is_public' => 1,
                'school_zone' => '',
                'ranking_city' => NULL,
                'ranking_state' => NULL,
                'ranking_city_5_years' => NULL,
                'ranking_state_5_years' => NULL,
                'school_img_url' => NULL,
            ),
             
            array (
                'id' => 89,
                'name' => 'Johnston Heights Secondary',
                'address' => '15350 - 99 Avenue',
                'city' => 'Surrey',
                'latitude' => '49.1823890',
                'longitude' => '-122.7967190',
                
                'type' => 1,
                'is_public' => 1,
                'school_zone' => '',
                'ranking_city' => NULL,
                'ranking_state' => NULL,
                'ranking_city_5_years' => NULL,
                'ranking_state_5_years' => NULL,
                'school_img_url' => NULL,
            ),
             
            array (
                'id' => 90,
                'name' => 'Windermere Secondary',
                'address' => '3155 E. 27th Ave',
                'city' => 'Vancouver',
                'latitude' => '49.2474730',
                'longitude' => '-123.0378460',
                
                'type' => 1,
                'is_public' => 1,
                'school_zone' => '',
                'ranking_city' => NULL,
                'ranking_state' => NULL,
                'ranking_city_5_years' => NULL,
                'ranking_state_5_years' => NULL,
                'school_img_url' => NULL,
            ),
             
            array (
                'id' => 91,
                'name' => 'MacNeill Secondary',
                'address' => '6611 No.4 Road',
                'city' => 'Richmond',
                'latitude' => '49.1642050',
                'longitude' => '-123.1151080',
                
                'type' => 1,
                'is_public' => 1,
                'school_zone' => '',
                'ranking_city' => NULL,
                'ranking_state' => NULL,
                'ranking_city_5_years' => NULL,
                'ranking_state_5_years' => NULL,
                'school_img_url' => NULL,
            ),
             
            array (
                'id' => 92,
                'name' => 'Sullivan Heights Secondary',
                'address' => '6248 - 144 Street',
                'city' => 'Surrey',
                'latitude' => '49.1159530',
                'longitude' => '-122.8230220',
                
                'type' => 1,
                'is_public' => 1,
                'school_zone' => '',
                'ranking_city' => NULL,
                'ranking_state' => NULL,
                'ranking_city_5_years' => NULL,
                'ranking_state_5_years' => NULL,
                'school_img_url' => NULL,
            ),
             
            array (
                'id' => 93,
                'name' => 'Tamanawis Secondary',
                'address' => '12600 - 66 Avenue',
                'city' => 'Surrey',
                'latitude' => '49.1225350',
                'longitude' => '-122.8717380',
                
                'type' => 1,
                'is_public' => 1,
                'school_zone' => '',
                'ranking_city' => NULL,
                'ranking_state' => NULL,
                'ranking_city_5_years' => NULL,
                'ranking_state_5_years' => NULL,
                'school_img_url' => NULL,
            ),
             
            array (
                'id' => 94,
                'name' => 'Sands Secondary',
                'address' => '10840 82 Avenue',
                'city' => 'Delta',
                'latitude' => '49.1518780',
                'longitude' => '-122.9227170',
                
                'type' => 1,
                'is_public' => 1,
                'school_zone' => '',
                'ranking_city' => NULL,
                'ranking_state' => NULL,
                'ranking_city_5_years' => NULL,
                'ranking_state_5_years' => NULL,
                'school_img_url' => NULL,
            ),
             
            array (
                'id' => 95,
                'name' => 'Gladstone Secondary',
                'address' => '4105 Gladstone St',
                'city' => 'Vancouver',
                'latitude' => '49.2486110',
                'longitude' => '-123.0616130',
                
                'type' => 1,
                'is_public' => 1,
                'school_zone' => '',
                'ranking_city' => NULL,
                'ranking_state' => NULL,
                'ranking_city_5_years' => NULL,
                'ranking_state_5_years' => NULL,
                'school_img_url' => NULL,
            ),
             
            array (
                'id' => 96,
                'name' => 'North Delta Secondary',
                'address' => '11447 82 Avenue',
                'city' => 'Delta',
                'latitude' => '49.1532800',
                'longitude' => '-122.9052060',
                
                'type' => 1,
                'is_public' => 1,
                'school_zone' => '',
                'ranking_city' => NULL,
                'ranking_state' => NULL,
                'ranking_city_5_years' => NULL,
                'ranking_state_5_years' => NULL,
                'school_img_url' => NULL,
            ),
             
            array (
                'id' => 97,
                'name' => 'Boyd Secondary',
                'address' => '9200 No. 1 Road',
                'city' => 'Richmond',
                'latitude' => '49.1460030',
                'longitude' => '-123.1813460',
                
                'type' => 1,
                'is_public' => 1,
                'school_zone' => '',
                'ranking_city' => NULL,
                'ranking_state' => NULL,
                'ranking_city_5_years' => NULL,
                'ranking_state_5_years' => NULL,
                'school_img_url' => NULL,
            ),
             
            array (
                'id' => 98,
                'name' => 'Cariboo Hill Secondary',
                'address' => '8580-16th Avenue',
                'city' => 'Burnaby',
                'latitude' => '49.2306580',
                'longitude' => '-122.9134920',
                
                'type' => 1,
                'is_public' => 1,
                'school_zone' => '',
                'ranking_city' => NULL,
                'ranking_state' => NULL,
                'ranking_city_5_years' => NULL,
                'ranking_state_5_years' => NULL,
                'school_img_url' => NULL,
            ),
             
            array (
                'id' => 99,
                'name' => 'Maple Ridge Secondary',
                'address' => '21911 - 122 Avenue',
                'city' => 'Maple Ridge',
                'latitude' => '49.2244150',
                'longitude' => '-122.6134260',
                
                'type' => 1,
                'is_public' => 1,
                'school_zone' => '',
                'ranking_city' => NULL,
                'ranking_state' => NULL,
                'ranking_city_5_years' => NULL,
                'ranking_state_5_years' => NULL,
                'school_img_url' => NULL,
            ),
             
            array (
                'id' => 100,
                'name' => 'Templeton Secondary',
                'address' => '727 Templeton Dr',
                'city' => 'Vancouver',
                'latitude' => '49.2773650',
                'longitude' => '-123.0598420',
                
                'type' => 1,
                'is_public' => 1,
                'school_zone' => '',
                'ranking_city' => NULL,
                'ranking_state' => NULL,
                'ranking_city_5_years' => NULL,
                'ranking_state_5_years' => NULL,
                'school_img_url' => NULL,
            ),
             
            array (
                'id' => 101,
                'name' => 'John Oliver Secondary',
                'address' => '530 E. 41st Ave',
                'city' => 'Vancouver',
                'latitude' => '49.2326980',
                'longitude' => '-123.0936270',
                
                'type' => 1,
                'is_public' => 1,
                'school_zone' => '',
                'ranking_city' => NULL,
                'ranking_state' => NULL,
                'ranking_city_5_years' => NULL,
                'ranking_state_5_years' => NULL,
                'school_img_url' => NULL,
            ),
             
            array (
                'id' => 102,
                'name' => 'Sir Charles Tupper Secondary',
                'address' => '419 E. 24th Ave',
                'city' => 'Vancouver',
                'latitude' => '49.2492790',
                'longitude' => '-123.0942100',
                
                'type' => 1,
                'is_public' => 1,
                'school_zone' => '',
                'ranking_city' => NULL,
                'ranking_state' => NULL,
                'ranking_city_5_years' => NULL,
                'ranking_state_5_years' => NULL,
                'school_img_url' => NULL,
            ),
             
            array (
                'id' => 103,
                'name' => 'Centennial Secondary',
                'address' => '570 Poirier St',
                'city' => 'Coquitlam',
                'latitude' => '49.2526760',
                'longitude' => '-122.8469920',
                
                'type' => 1,
                'is_public' => 1,
                'school_zone' => '',
                'ranking_city' => NULL,
                'ranking_state' => NULL,
                'ranking_city_5_years' => NULL,
                'ranking_state_5_years' => NULL,
                'school_img_url' => NULL,
            ),
             
            array (
                'id' => 104,
                'name' => 'Cambie Secondary',
                'address' => '4151 Jacombs Road',
                'city' => 'Richmond',
                'latitude' => '49.1834410',
                'longitude' => '-123.0814860',
                
                'type' => 1,
                'is_public' => 1,
                'school_zone' => '',
                'ranking_city' => NULL,
                'ranking_state' => NULL,
                'ranking_city_5_years' => NULL,
                'ranking_state_5_years' => NULL,
                'school_img_url' => NULL,
            ),
             
            array (
                'id' => 105,
                'name' => 'Aldergrove Secondary',
                'address' => '26850 - 29th Avenue',
                'city' => 'Aldergrove',
                'latitude' => '49.0556050',
                'longitude' => '-122.4809250',
                
                'type' => 1,
                'is_public' => 1,
                'school_zone' => '',
                'ranking_city' => NULL,
                'ranking_state' => NULL,
                'ranking_city_5_years' => NULL,
                'ranking_state_5_years' => NULL,
                'school_img_url' => NULL,
            ),
             
            array (
                'id' => 106,
                'name' => 'Kwantlen Park Secondary',
                'address' => '10441 - 132 Street',
                'city' => 'Surrey',
                'latitude' => '49.1925180',
                'longitude' => '-122.8578130',
                
                'type' => 1,
                'is_public' => 1,
                'school_zone' => '',
                'ranking_city' => NULL,
                'ranking_state' => NULL,
                'ranking_city_5_years' => NULL,
                'ranking_state_5_years' => NULL,
                'school_img_url' => NULL,
            ),
             
            array (
                'id' => 107,
                'name' => 'Burnaby South Secondary',
                'address' => '5455 Rumble Street',
                'city' => 'Burnaby',
                'latitude' => '49.2160800',
                'longitude' => '-122.9851510',
                
                'type' => 1,
                'is_public' => 1,
                'school_zone' => '',
                'ranking_city' => NULL,
                'ranking_state' => NULL,
                'ranking_city_5_years' => NULL,
                'ranking_state_5_years' => NULL,
                'school_img_url' => NULL,
            ),
             
            array (
                'id' => 108,
                'name' => 'Langley Secondary',
                'address' => '21405 - 56th Avenue',
                'city' => 'Langley',
                'latitude' => '49.1047390',
                'longitude' => '-122.6303820',
                
                'type' => 1,
                'is_public' => 1,
                'school_zone' => '',
                'ranking_city' => NULL,
                'ranking_state' => NULL,
                'ranking_city_5_years' => NULL,
                'ranking_state_5_years' => NULL,
                'school_img_url' => NULL,
            ),
             
            array (
                'id' => 109,
                'name' => 'Clayton Heights Secondary',
                'address' => '7003 - 188 Street',
                'city' => 'Surrey',
                'latitude' => '49.1292150',
                'longitude' => '-122.7019140',
                
                'type' => 1,
                'is_public' => 1,
                'school_zone' => '',
                'ranking_city' => NULL,
                'ranking_state' => NULL,
                'ranking_city_5_years' => NULL,
                'ranking_state_5_years' => NULL,
                'school_img_url' => NULL,
            ),
             
            array (
                'id' => 110,
                'name' => 'Delview Secondary',
                'address' => '9111 116 Street',
                'city' => 'Delta',
                'latitude' => '49.1686290',
                'longitude' => '-122.9003830',
                
                'type' => 1,
                'is_public' => 1,
                'school_zone' => '',
                'ranking_city' => NULL,
                'ranking_state' => NULL,
                'ranking_city_5_years' => NULL,
                'ranking_state_5_years' => NULL,
                'school_img_url' => NULL,
            ),
             
            array (
                'id' => 111,
                'name' => 'Alpha Secondary',
                'address' => '4600 Parker Street',
                'city' => 'Burnaby',
                'latitude' => '49.2759360',
                'longitude' => '-122.9982710',
                
                'type' => 1,
                'is_public' => 1,
                'school_zone' => '',
                'ranking_city' => NULL,
                'ranking_state' => NULL,
                'ranking_city_5_years' => NULL,
                'ranking_state_5_years' => NULL,
                'school_img_url' => NULL,
            ),
             
            array (
                'id' => 112,
                'name' => 'Thomas Haney Secondary',
                'address' => '23000 - 116 Avenue',
                'city' => 'Maple Ridge',
                'latitude' => '49.2125930',
                'longitude' => '-122.5821660',
                
                'type' => 1,
                'is_public' => 1,
                'school_zone' => '',
                'ranking_city' => NULL,
                'ranking_state' => NULL,
                'ranking_city_5_years' => NULL,
                'ranking_state_5_years' => NULL,
                'school_img_url' => NULL,
            ),
             
            array (
                'id' => 113,
                'name' => 'Frank Hurt Secondary',
                'address' => '13940 - 77 Avenue',
                'city' => 'Surrey',
                'latitude' => '49.1419350',
                'longitude' => '-122.8367340',
                
                'type' => 1,
                'is_public' => 1,
                'school_zone' => '',
                'ranking_city' => NULL,
                'ranking_state' => NULL,
                'ranking_city_5_years' => NULL,
                'ranking_state_5_years' => NULL,
                'school_img_url' => NULL,
            ),
             
            array (
                'id' => 114,
                'name' => 'Killarney Secondary',
                'address' => '6454 Killarney St',
                'city' => 'Vancouver',
                'latitude' => '49.2250470',
                'longitude' => '-123.0447600',
                
                'type' => 1,
                'is_public' => 1,
                'school_zone' => '',
                'ranking_city' => NULL,
                'ranking_state' => NULL,
                'ranking_city_5_years' => NULL,
                'ranking_state_5_years' => NULL,
                'school_img_url' => NULL,
            ),
             
            array (
                'id' => 115,
                'name' => 'Sutherland Secondary',
                'address' => '1860 Sutherland Avenue',
                'city' => 'North Vancouver',
                'latitude' => '49.3259410',
                'longitude' => '-123.0529740',
                
                'type' => 1,
                'is_public' => 1,
                'school_zone' => '',
                'ranking_city' => NULL,
                'ranking_state' => NULL,
                'ranking_city_5_years' => NULL,
                'ranking_state_5_years' => NULL,
                'school_img_url' => NULL,
            ),
             
            array (
                'id' => 116,
                'name' => 'Britannia Secondary',
                'address' => '1001 Cotton Dr',
                'city' => 'Vancouver',
                'latitude' => '49.2760650',
                'longitude' => '-123.0710930',
                
                'type' => 1,
                'is_public' => 1,
                'school_zone' => '',
                'ranking_city' => NULL,
                'ranking_state' => NULL,
                'ranking_city_5_years' => NULL,
                'ranking_state_5_years' => NULL,
                'school_img_url' => NULL,
            ),
             
            array (
                'id' => 117,
                'name' => 'Westview Secondary',
                'address' => '20905 Wicklund Avenue',
                'city' => 'Maple Ridge',
                'latitude' => '49.2245370',
                'longitude' => '-122.6419780',
                
                'type' => 1,
                'is_public' => 1,
                'school_zone' => '',
                'ranking_city' => NULL,
                'ranking_state' => NULL,
                'ranking_city_5_years' => NULL,
                'ranking_state_5_years' => NULL,
                'school_img_url' => NULL,
            ),
             
            array (
                'id' => 118,
                'name' => 'Carson Graham Secondary',
                'address' => '2145 Jones Avenue',
                'city' => 'North Vancouver',
                'latitude' => '49.3290150',
                'longitude' => '-123.0817840',
                
                'type' => 1,
                'is_public' => 1,
                'school_zone' => '',
                'ranking_city' => NULL,
                'ranking_state' => NULL,
                'ranking_city_5_years' => NULL,
                'ranking_state_5_years' => NULL,
                'school_img_url' => NULL,
            ),
             
            array (
                'id' => 119,
                'name' => 'McNair Secondary',
                'address' => '9500 No. 4 Road',
                'city' => 'Richmond',
                'latitude' => '49.1424650',
                'longitude' => '-123.1137910',
                
                'type' => 1,
                'is_public' => 1,
                'school_zone' => '',
                'ranking_city' => NULL,
                'ranking_state' => NULL,
                'ranking_city_5_years' => NULL,
                'ranking_state_5_years' => NULL,
                'school_img_url' => NULL,
            ),
             
            array (
                'id' => 120,
                'name' => 'Guildford Park Secondary',
                'address' => '10707 - 146 Street ',
                'city' => 'Surrey',
                'latitude' => '49.1970220',
                'longitude' => '-122.8188900',
                
                'type' => 1,
                'is_public' => 1,
                'school_zone' => '',
                'ranking_city' => NULL,
                'ranking_state' => NULL,
                'ranking_city_5_years' => NULL,
                'ranking_state_5_years' => NULL,
                'school_img_url' => NULL,
            ),
             
            array (
                'id' => 121,
                'name' => 'Queen Elizabeth Secondary',
                'address' => '9457 - King George Blvd',
                'city' => 'Surrey',
                'latitude' => '49.1740500',
                'longitude' => '-122.8461900',
                
                'type' => 1,
                'is_public' => 1,
                'school_zone' => '',
                'ranking_city' => NULL,
                'ranking_state' => NULL,
                'ranking_city_5_years' => NULL,
                'ranking_state_5_years' => NULL,
                'school_img_url' => NULL,
            ),
             
            array (
                'id' => 122,
                'name' => 'Pitt Meadows Secondary',
                'address' => '19438 - 116B Avenue',
                'city' => 'Pitt Meadows',
                'latitude' => '49.2144190',
                'longitude' => '-122.6837880',
                
                'type' => 1,
                'is_public' => 1,
                'school_zone' => '',
                'ranking_city' => NULL,
                'ranking_state' => NULL,
                'ranking_city_5_years' => NULL,
                'ranking_state_5_years' => NULL,
                'school_img_url' => NULL,
            ),
             
            array (
                'id' => 123,
                'name' => 'Byrne Creek Secondary',
                'address' => '7777 18th Street',
                'city' => 'Burnaby',
                'latitude' => '49.2077570',
                'longitude' => '-122.9504870',
                
                'type' => 1,
                'is_public' => 1,
                'school_zone' => '',
                'ranking_city' => NULL,
                'ranking_state' => NULL,
                'ranking_city_5_years' => NULL,
                'ranking_state_5_years' => NULL,
                'school_img_url' => NULL,
            ),
             
            array (
                'id' => 124,
                'name' => 'Samuel Robertson Secondary',
                'address' => '10445 - 245th Street',
                'city' => 'Maple Ridge',
                'latitude' => '49.1918010',
                'longitude' => '-122.5428110',
                
                'type' => 1,
                'is_public' => 1,
                'school_zone' => '',
                'ranking_city' => NULL,
                'ranking_state' => NULL,
                'ranking_city_5_years' => NULL,
                'ranking_state_5_years' => NULL,
                'school_img_url' => NULL,
            ),
             
            array (
                'id' => 125,
                'name' => 'King George Secondary',
                'address' => '1755 Barclay St',
                'city' => 'Vancouver',
                'latitude' => '49.2899130',
                'longitude' => '-123.1360740',
                
                'type' => 1,
                'is_public' => 1,
                'school_zone' => '',
                'ranking_city' => NULL,
                'ranking_state' => NULL,
                'ranking_city_5_years' => NULL,
                'ranking_state_5_years' => NULL,
                'school_img_url' => NULL,
            ),
             
            array (
                'id' => 126,
                'name' => 'Garibaldi Secondary',
                'address' => '24789 Dewdney Trunk Road',
                'city' => 'Maple Ridge',
                'latitude' => '49.2205490',
                'longitude' => '-122.5354850',
                
                'type' => 1,
                'is_public' => 1,
                'school_zone' => '',
                'ranking_city' => NULL,
                'ranking_state' => NULL,
                'ranking_city_5_years' => NULL,
                'ranking_state_5_years' => NULL,
                'school_img_url' => NULL,
            ),
             
            array (
                'id' => 127,
                'name' => 'L. A. Matheson Secondary',
                'address' => '9484 - 122 Street ',
                'city' => 'Surrey',
                'latitude' => '49.1752910',
                'longitude' => '-122.8843970',
                
                'type' => 1,
                'is_public' => 1,
                'school_zone' => '',
                'ranking_city' => NULL,
                'ranking_state' => NULL,
                'ranking_city_5_years' => NULL,
                'ranking_state_5_years' => NULL,
                'school_img_url' => NULL,
            ),
             
            array (
                'id' => 128,
                'name' => 'Bodwell Academy',
                'address' => '955 Harbourside Dr',
                'city' => 'North Vancouver',
                'latitude' => '49.3142540',
                'longitude' => '-123.1005260',
                
                'type' => 1,
                'is_public' => 0,
                'school_zone' => '',
                'ranking_city' => NULL,
                'ranking_state' => NULL,
                'ranking_city_5_years' => NULL,
                'ranking_state_5_years' => NULL,
                'school_img_url' => NULL,
            ),
             
            array (
                'id' => 129,
                'name' => 'St John\'s International',
                'address' => '300-1885 Broadway W',
                'city' => 'Vancouver',
                'latitude' => '49.2638900',
                'longitude' => '-123.1477400',
                
                'type' => 1,
                'is_public' => 0,
                'school_zone' => '',
                'ranking_city' => NULL,
                'ranking_state' => NULL,
                'ranking_city_5_years' => NULL,
                'ranking_state_5_years' => NULL,
                'school_img_url' => NULL,
            ),
        ));
        
        
    }
}
